# Generated by Django 5.1.6 on 2025-02-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('blood_type_needed', models.CharField(max_length=5)),
                ('hospital_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('blood_type', models.CharField(max_length=5)),
                ('contact_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
