# Generated by Django 5.1.6 on 2025-02-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='contact_number',
            new_name='phone_number',
        ),
    ]
