# Generated by Django 4.0.6 on 2025-04-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_contact_number_bloodrequest_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='city',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
